version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: stone-inventory-app
    container_name: stone-inventory-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - stone-inv-network

  nginx:
    image: nginx:alpine
    container_name: stone-inventory-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - stone-inv-network

networks:
  stone-inv-network:
    driver: bridge
